prevent dropdown from sticking over right screen edge
kiwigrid/kiwi-components pull request #48
Opened 2022-01-19 14:50 UTC by christian-steinert-kiwigrid

Support situations where the dropdown menu sticks to the screen edge:
In these situation the dropdown is now shifted to the left somewhat so that it ends at the right screen edge without causing horizontal scrolling

2022-01-19 15:54 UTC, reins-ch requested changes

2022-01-19 15:54 UTC, reins-ch commented on packages/atoms/src/components/kiwi-dropdown/kiwi-dropdown.tsx
> +      const dropdown = this.el.querySelector('.dropdown-menu') as HTMLElement;
Anstatt `@Element()` und dann darin zu suchen, kannst du gleich an dem `div.dropdown-menu` das `ref`-Attribut setzen. Siehe https://stenciljs.com/docs/templating-jsx#getting-a-reference-to-a-dom-element

Das geht natürlich in anderen Fällen nicht, wo das gewünschte Element nicht in der render-Methode derselben Komponente auftaucht.

2022-01-19 15:54 UTC, reins-ch commented on packages/atoms/src/components/kiwi-dropdown/kiwi-dropdown.tsx
> +          }
Die Konditionen würde ich gern noch mehr entschachteln.
```js
if (this.open) {
  const rect = dropdown.getBoundingClientRect()
  
  const offset = rect.width > window.visualViewport.width 
    ? Math.floor(rect.left) 
    : Math.ceil(rect.right - window.visualViewport.width)
  // translate setzen wie bisher
} else {
  // wie bisher
}
```
vgl. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator

2022-01-19 15:54 UTC, reins-ch commented on packages/atoms/src/components/kiwi-checkbox-dropdown-menu/kiwi-checkbox-dropdown-menu.stories.js
> +    <div class="panel-body" style="text-align:right">
```suggestion
    <div class="panel-body pull-right">
```
Ich hoffe das funktioniert so, ansonsten musst du die Klasse `pull-right` mal bei einem Kindelement setzen.

2022-01-20 09:22 UTC, thccorni commented
Die commit msg entspricht nicht den Regeln von conventional commits, vermutlich führt das an irgendeiner Stelle zu Problemen. Ich hätte gedacht das wird durch einen commit hook verhindert 🤔

2022-01-20 10:40 UTC, reins-ch commented
> Die commit msg entspricht nicht den Regeln von conventional commits, vermutlich führt das an irgendeiner Stelle zu Problemen. Ich hätte gedacht das wird durch einen commit hook verhindert thinking

Guter Fund. Das ist mir gar nicht aufgefallen. Ich bin da auch gerade ratlos.

Was außerdem noch nicht stimmt ist, dass CircleCI den PR nicht baut. Ich hoffe das liegt nicht daran, dass der PR aus einem Fork stammt.

2022-01-20 12:40 UTC, reins-ch requested changes

2022-01-20 12:40 UTC, reins-ch commented on packages/atoms/src/components/kiwi-dropdown/kiwi-dropdown.tsx
> +          ref={(el) => (this.dropdownEl = el as HTMLInputElement)}
Ha, erwischt! Da hat wohl einer Copy+Paste gemacht ;-P

2022-01-20 12:40 UTC, reins-ch commented on packages/atoms/src/components/kiwi-dropdown/kiwi-dropdown.tsx
>      // make sure that the dropdown does not stick over the right edge of the body
Der Kommentar ist besser als Funktionsbeschreibung aufgehoben.

2022-01-20 12:40 UTC, reins-ch commented on packages/atoms/src/components/kiwi-dropdown/kiwi-dropdown.tsx
>          if (offset > 0) {
Sollte jetzt unnötig sein, wenn ich mir die Vergleiche und Zuweisungen so ansehe.
- `rect.left` sollte immer positiv sein.
- Wenn das Rect breiter als der Viewport ist, dann ist die Differenz immer positiv.

2022-01-20 20:12 UTC, closed without merging

2022-01-20 20:13 UTC, christian-steinert-kiwigrid commented
Changes will be re-submitted. Closing this PR.